# This is a collection of Http-Requests to the connections ressource.
# It can be used with IntelliJs HttpClient to do End-to-End-Testing of the Config-Server Endpoints.
# Run the server and just start the collection.

### GET request to retrieve all connections
GET http://localhost:8080/api/v1/connections

### POST request to connections without fields

POST http://127.0.0.1:8080/api/v1/connections

### POST request to connections with missing fields
 POST http://127.0.0.1:8080/api/v1/connections
Content-Type: application/json

{
    "javaVersion": "17",
    "gepardVersion": "0.0.1-SNAPSHOT",
    "startTime":  1719850971,
    "pid": 432423

}

### POST request to connections with all fields
POST http://127.0.0.1:8080/api/v1/connections
Content-Type: application/json

{
  "serviceName": "test-service",
  "otelVersion": "1.2.5",
  "javaVersion": "17",
  "gepardVersion": "0.0.1-SNAPSHOT",
  "startTime": 1719850971,
  "pid": 432423,
  "attributes": {
    "custom": "property"
  }
}

> {% client.global.set("response_redirect", response.headers.valueOf('Location')); %}

### GET request to connections/{id}
GET {{response_redirect}}

### POST request to connections/query
POST http://127.0.0.1:8080/api/v1/connections/query
Content-Type:  application/json

{
  "serviceName": "test-service",
  "otelVersion": "1.2.5",
  "attributes": {
    "custom": "property"
  }
}

