name: Master Branch Continuous Release

on:
  push:
    branches:
      - master
      - feature/vhvapm-547

env:
  REGISTRY_IMAGE: inspectit/inspectit-gepard-agent

jobs:
  build-jar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
        with:
          build-scan-publish: true
          build-scan-terms-of-service-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-service-agree: "yes"

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: agent-artifact
          path: backend/build/libs/backend-0.0.1-SNAPSHOT.jar